# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creator',
        ),
    ]
