# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_comment_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.CharField(default='Unknown creator', max_length=50),
            preserve_default=False,
        ),
    ]
